---

- hosts: master
  user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - { role: init }
    - { role: cert }
    - { role: docker-registry }
    - { role: java }
    - { role: jenkins }
    # - { role: elasticsearch }
    - { role: containerd }
    - { role: kubernetes }
    - { role: docker }

  vars:
    # jenkins_hostname: jenkins.example.com
    kubernetes_role: master
    kubernetes_apiserver_advertise_address: 192.168.10.10
    # ismaster: "yes"
    cert_dir: cert
    java_packages: openjdk-11-jdk
    docker_users: ["vagrant"]

- hosts: worker
  user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - { role: init }
    - { role: cert }
    - { role: containerd }
    - { role: kubernetes }
    
  vars:
    # jenkins_hostname: jenkins.example.com
    kubernetes_role: node
    kubernetes_apiserver_advertise_address: 192.168.10.10
    cert_dir: cert
    java_packages: openjdk-11-jdk

- hosts: master
  user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - { role: cert }
    - { role: helmingress }
  
  vars:
    ismaster: "yes"
    cert_dir: cert